# Generated by Django 4.1.1 on 2022-09-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_delete_skills_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
